### ISSUE TITLE
Feature Request: Support Structural Schemas for CRDs

### ISSUE THREAD

**Issue by flickerfly** [operator-framework/operatorhub.io#214]
Structural Schemas for CRDs were [described in a Kubernetes blog](https://kubernetes.io/blog/2019/06/20/crd-structural-schema/) back in June.

It would be really great if the CRD presentation showed the information that the new schema provides so that users can make more intelligent decisions regarding their input and what is acceptable. This schema data is already being put into the bundles that are being consumed, it just needs to be presented. Perhaps a first step would be just to show that it exists and give a link to the CRD in the git repo to check it out.

As an example of the schema input already available:
https://github.com/operator-framework/community-operators/blob/master/upstream-community-operators/ibmcloud-operator/ibmcloud_operator_v1alpha1_service.crd.yaml

How that CRD is currently presented:
https://operatorhub.io/operator/ibmcloud-operator

**Comment by dmesser** [comment]
Can you elaborate on what you think would be the best way to show this? Right now we serve ready-to-go examples so people can get started. How would someone using operatorhub.io best consume structure CRD info?

**Comment by flickerfly** [comment]
Sure.

I imagine a table being created for the items in the schema. I'll use the example from the blog post, fleshed out to show some fields they didn't use. 

```
type: object
properties:
  spec:
    type: object
    properties
      command:
        type: string
        minLength: 1                          # value validation
        description: cron command to run
      shell:
        title: Shell
        description: The shell the command runs as 
        type: string
        minLength: 1                          # value validation
      machines:
        type: array
        items:
          type: string
          pattern: “^[a-z0-9]+(-[a-z0-9]+)*$” # value validation
    oneOf:                                    # value validation
    - required: [“command”]                   # value validation
    - required: [“shell”]                     # value validation
required: [“spec”]                            # value validation
```
I'd expect the above to be presented something like below, but pretty:
```
| field name     | type   | description         | pattern                  | minLength | required |
| shell          | string | The shell the command runs as | *              | 1         |    yes   |
| command        | string | cron command to run | *                        | 1         |    yes   |
| machines       | array  | none                | *                        | *         |          |
| machines.items | string | none                | ^[a-z0-9]+(-[a-z0-9]+)*$ |           |          |


```

Here's another blog entry from Red Hat about these:
https://blog.openshift.com/a-look-into-the-technical-details-of-kubernetes-1-16/
